import type { Metadata } from "next"
import YamadaProvider from "@/provider/yamada";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <YamadaProvider>
            {children}
          </YamadaProvider>
        </body>
    </html>
  );
}
